language: python
python:
  - "2.7"
before_script:
  - openssl aes-256-cbc -K $encrypted_5e9a1583941e_key -iv $encrypted_5e9a1583941e_iv -in test/test.cfg.enc -out test/test.cfg -d
script:
  - cd test 
  - python -m unittest test.TestPotato411

